export const searchLoadingData = [
    {id: 1, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 2, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 3, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 4, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 5, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 6, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 7, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 8, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 9, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 10, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 11, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 12, title: '', description: '', cityId: 1, owner: 1, price: 3000,propertyType: "", main_image: "images/loadingApartment.jpg", images: ["images/apartment/apartment_1.jpg", "images/apartment/apartment_2.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_4.jpg", "images/apartment/apartment_5.jpg"], number_of_beds: 3, number_of_rooms: 4, address: '', sqft: 7500, status: 2, for_rent: false,for_sale: true},
  ];